spring.application.name=spring-mcp
spring.ai.mcp.server.name=springmcp
spring.ai.mcp.server.version=0.1.1

spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=sync

